name: bio_attendance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  cloud_firestore: ^4.14.0
  crypto: ^3.0.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  google_mlkit_face_detection: ^0.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http:
  image_picker: ^1.0.7
  local_auth: ^2.1.8
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  provider: ^6.1.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/admin.png
    - assets/images/lecturer.png
    - assets/images/student.png
    - assets/images/search.png
    - assets/images/add_user.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.ttf
