// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY-fJ4ePbBvfuO_Do0mwFEqySG9bGye78',
    appId: '1:112340355748:web:389096c9ea9c3cbff4b431',
    messagingSenderId: '112340355748',
    projectId: 'bio-metric-attendance-app',
    authDomain: 'bio-metric-attendance-app.firebaseapp.com',
    storageBucket: 'bio-metric-attendance-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARMkO5DaU3H19ZCXargNWwPuQ-KvHep-c',
    appId: '1:112340355748:android:a330861cdebfabe0f4b431',
    messagingSenderId: '112340355748',
    projectId: 'bio-metric-attendance-app',
    storageBucket: 'bio-metric-attendance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwym47bRd-ItIgb9Jv-Lz0jrT_x8aD0KM',
    appId: '1:112340355748:ios:11e13a2d5696b234f4b431',
    messagingSenderId: '112340355748',
    projectId: 'bio-metric-attendance-app',
    storageBucket: 'bio-metric-attendance-app.appspot.com',
    iosBundleId: 'com.example.bioAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwym47bRd-ItIgb9Jv-Lz0jrT_x8aD0KM',
    appId: '1:112340355748:ios:957311af6698c45af4b431',
    messagingSenderId: '112340355748',
    projectId: 'bio-metric-attendance-app',
    storageBucket: 'bio-metric-attendance-app.appspot.com',
    iosBundleId: 'com.example.bioAttendance.RunnerTests',
  );
}
